### ISSUE TITLE
Crash when executing 

### ISSUE THREAD

**Issue by aradove** [foxmask/baeuda#5]
Error while importing notes from joplin to anki. 

![image](https://user-images.githubusercontent.com/9294134/64319712-4b439680-cfbd-11e9-95a6-d5b53e39ca4f.png)

Settings file:
```
JOPLIN_WEBCLIPPER = 41184
TOKEN = '94a750d8cd0b85eeb6d3e07ad5463ef1539858c3faab92ff90c27117dd468fb71a1863e8ec64b24bd6ade7a39b2bb613afa4f92f91c3948aab5cde5d92bef706'
FOLDER = 'ML'
PYPANDOC_MARKDOWN = 'markdown_github'
FILTER = ''
ANKI_URL = 'http://localhost:8765/'
ANKI_MODEL = 'Basic'  # fields are front/back/romanisation
ANKI_FIELD_COUNT = 2   # number of columns to grab from a joplin table
ANKI_FIELDS = ['Front', 'Back']
ONE_DECK_PER_NOTE = False    # will create one deck
```

Error while running:
```
$ python3 baeuda/anki.py 
ML - front - back
Traceback (most recent call last):
  File "baeuda/anki.py", line 143, in <module>
    loop.run_until_complete(anki())
  File "/home/martin/miniconda3/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "baeuda/anki.py", line 138, in anki
    lines += (line3.text, )
UnboundLocalError: local variable 'lines' referenced before assignment
(bauda) (base) martin@martin-laptop:~/program/joplin-anki converter/bauda/baeuda$ python3 baeuda/anki.py 
ML - front - back
{} ['front', 'back']

```

**Comment by foxmask** [comment]
`ANKI_FIELDS` should contain the names of each column, so in your case 
```
ANKI_FIELDS = ['HeadingA', 'HeadingB']
```
